### ISSUE TITLE
.frame() modifier shifts the calendar to the right if used with .horozontal() scrolling

### ISSUE THREAD

**Issue by maray29** [ThasianX/ElegantCalendar#11]
Hi, 

I saw the horizontal monthly calendar scrolling was implemented recently which is cool. Although when you apply .frame() modifier to MonthlyCalendarView it is being shifted to the right. Please see the screenshot. I guess it is related to ElegantPages? Could you point me in the right direction and I would try to find the issue. 

I am new to coding and it's the first time I submit an issue, please tell me if I did something wrong. 
It's a very cool calendar library, trying to implement it in the habit tracker app I am working on.

<img width="1317" alt="Screenshot 2020-08-06 at 21 53 32" src="https://user-images.githubusercontent.com/63769810/89559710-7bc82c00-d82f-11ea-820d-ea31abab8c09.png">

**Comment by ThasianX** [comment]
Try removing your `VStack`'s alignment. Also, idk why you have it embedded inside 2 `VStacks` in the first place. And I would recommend that you don't make the calendar smaller than like 90% of the screen width. The smaller it gets, the uglier it'll look. This calendar is meant to be a full screen one but I did add some leeway in case you want to slightly make it smaller and such.

**Comment by maray29** [comment]
It works as expected with the default vertical scrolling, but is shifted when is changed to horizontal. VStack alignment does not change anything either. It can also be made slightly smaller with padding. I was just testing and noticed this behaviour, if it's not relevant, then the issue can be closed.

**Comment by ThasianX** [comment]
that's weird. i literally just used ur exact same code and it works for me. the calendar is center aligned but just smaller. try running that on the simulator

**Comment by maray29** [comment]
Hi Kevin, I think it's Xcode 12 and iOS14 issue, it's working well on Xcode 11. Since it's not yet fully supported and the .frame modifier was meant for slight size changes then I think we can close the issue and don't waste time. Thanks for your help!
