### ISSUE TITLE
Minimum deploy target

### ISSUE THREAD

**Issue by hectorhm98** [ThasianX/ElegantCalendar#17]
Hi, I was worrying if there's a way to use this calendar for lower versions of iOS such as 11.4 or at least 12 instead of 13 (even though the major part of iOS user are above 13, there are some still in 12. 
Thanks beforehand.

**Comment by ThasianX** [comment]
Nope. iOS 13 > only. I wouldn’t worry about 12 by it’s like 6% of users on that
