### ISSUE TITLE
Collapse to week

### ISSUE THREAD

**Issue by fer112233** [ThasianX/ElegantCalendar#19]
Hi, would it be possible to collapse the calendar view to see only the week instead of the whole month? This way there would be more space for content.
Something similar to this from FSCalendar:
![image](https://user-images.githubusercontent.com/19349431/92209997-43e3f100-ee8e-11ea-966c-18637f0a8987.gif)

Thank you

**Comment by jimmyKouch** [comment]
I was wondering the same thing!! Maybe just the week view without the toggle option... is there any way to do that from the source code?

**Comment by ThasianX** [comment]
It's possible but it would take a lot of labor to write the code for that. When I initially wrote the library, I didn't think of adding flexibility to the actual calendar view component. There's a lot of flexibility in the custom view component however.
