### ISSUE TITLE
Incorrent week days in regions with first week day other than sunday

### ISSUE THREAD

**Issue by MatoC9** [ThasianX/ElegantCalendar#22]
I am a new user user to ElegantCalendar, but I have noticed that the legend for week days don't match the actual week day of dates.
In my region monday is the first day of the week, but on top of the calendar it still shows "S M T W T F S", but it should show "M T W T F S S" as the days are shown in the correct "column" (monday is first in this case).

![ElegantCalendar](https://user-images.githubusercontent.com/11889759/93798492-0dec8e00-fc3e-11ea-8973-405c8c4f7b0f.png)

**Comment by ThasianX** [comment]
Thanks for pointing this out! Just fixed this on the latest release. Let me know if it works for you

**Comment by MatoC9** [comment]
Yeah, it's working fine for me now. Sorry for such a late response.
