### ISSUE TITLE
Dynamic 'startDate' and 'endDate'

### ISSUE THREAD

**Issue by thrustToga** [ThasianX/ElegantCalendar#24]
Is there any way to change startDate and endDate dynamically? 

I was looking into the source code and found a line in CalendarConfiguration.swift: "/// Any changes to the configuration will reset the calendar based on its new settings" 

But I didn't understand how to do it. First, the CalendarConfiguration have let property itself in MontlyCalendarManager and in the CalendarConfiguration struct the startDate and endDate properties are also have let

When I change them to var, the dates changes, but the months remain the same. In which direction should I move?

**Comment by ThasianX** [comment]
If you want dynamic start and end dates, you should make them `@State` variables. Pass those state variables as parameters into the `CalendarConfiguration` and when those states change, the calendar should refresh

**Comment by zaeem-khatib** [comment]
`CalendarConfiguration` method does not accept `@State` variables as input parameters, it accepts a `Date` object. I am not sure how to set the start and end dates of the calendar dynamically.
