### ISSUE TITLE
Change Circle Color when Date is Clicked

### ISSUE THREAD

**Issue by nululalbab** [ThasianX/ElegantCalendar#26]
I used your package in xcode 14 and I wanted to edit the CircularSelectionView in DayView but isee that the Circle() color is set to color.primary. Any ideas how to edit this Circle? Trying to edit the Theme to my own color and Successfull, but i cant change this bounce circle

![image](https://user-images.githubusercontent.com/29245325/96069654-dbdeec80-0ec8-11eb-9504-f6e27f5fff9c.png)

**Comment by ThasianX** [comment]
You can add a `let theme: Color` to the View and make the circle consume it through `Circle().stroke(theme, lineWidth: 2)`
