### ISSUE TITLE
reload data

### ISSUE THREAD

**Issue by yuyedaidao** [ThasianX/ElegantCalendar#28]
When I fetched data from server, what I should do to reload datasource

**Comment by ThasianX** [comment]
It should automatically reload, as long as your datasource is a state variable

**Comment by sranipa** [comment]
Hi @ThasianX , I am using ElegantTimeline-SwiftUI, Where we need to create State variable for server data reload ? I mean in MonthlyCalendarDataSource, YearlyCalendarDataSource or ElegantCalendarDataSource ?

I tried but it is not working for me, Can you please help me out in this ?

**Comment by ThasianX** [comment]
Create an @State variable in the same component or a parent component that implements the calendar
