### ISSUE TITLE
how to add color coded for specific days ?

### ISSUE THREAD

**Issue by Darren120** [ThasianX/ElegantCalendar#29]
I want to add a color code on important dates, both in month and whole year view. is it possible?

is it possible to have an array of dates to be colored on the calender differently? pls add if cant ty.

**Comment by ThasianX** [comment]
It is possible but the library currently only supports adding color coded dates to days. If you want to highlight a whole month or year, you will have to fork the library and add the code yourself

**Comment by Darren120** [comment]
> It is possible but the library currently only supports adding color coded dates to days. If you want to highlight a whole month or year, you will have to fork the library and add the code yourself

yah, I don't need an entire month, just days and shows during year view as well..

**Comment by ThasianX** [comment]
> yah, I don't need an entire month, just days and shows during year view as well..

Oh I see what you mean now. The library doesn't support what you want yet. If you want that functionality, you just need to add the same checks the DayView does in the month and year view to highlight a certain day.
