### ISSUE TITLE
Title do not show up

### ISSUE THREAD

**Issue by diogo10** [ThasianX/ElegantCalendar#30]
Hi guys, I just got the code of the demo and customised as needed. Sent that code to another project and got that:

![Screenshot 2021-02-12 at 15 27 15](https://user-images.githubusercontent.com/1541244/107788543-700e7280-6d48-11eb-98de-ac367cbde66b.png)

I can not find any reason for that. I am using the kiwiGreen theme.

`let configuration = CalendarConfiguration(
                calendar: currentCalendar,
                startDate: ascVisits.first!.theDate,
                endDate: ascVisits.last!.theDate)

            calendarManager = ElegantCalendarManager(
                configuration: configuration,
                initialMonth: initialMonth)

            visitsByDay = Dictionary(
                grouping: ascVisits,
                by: { currentCalendar.startOfDay(for: $0.theDate) })

            calendarManager.datasource = self
            calendarManager.delegate = self
            
`

`
var body: some View {
           VStack {
            
               ElegantCalendarView(calendarManager: calendarManager)
                .theme(calendarTheme).horizontal()
            Spacer()
           }
       }
`

Maybe, the NavigationView?

**Comment by ThasianX** [comment]
Yea this has to do with your navigation view. The library is meant to be used in conjunction with swipe transitions vs stack transitions.
