### ISSUE TITLE
Days of the Week appear correctly on Simulator but not on device.

### ISSUE THREAD

**Issue by yomagicdev** [ThasianX/ElegantCalendar#32]
Great job on developing this project. The calendar looks wonderful!

I am experiencing a strange issue with the example project where the start of the month doesn't match up with the actual days of the week in the Monthly Calendar view.
Here is the screenshot from my simulator:
![Simulator Screen Shot - iPod touch (7th generation) - 2021-03-03 at 15 45 48](https://user-images.githubusercontent.com/79991526/109831892-c2e89500-7c37-11eb-9bfb-e8aa038ac8f5.png)

As you can see, today is Wednesday 3 March 2021 and the calendar view is aligned correctly with the days of the week.

However, when I run the example project on my iPhoneX it shows this:
![IMG_2B5E38DCFEF7-1](https://user-images.githubusercontent.com/79991526/109832245-15c24c80-7c38-11eb-9aef-b5ebd753524c.jpeg)

As you can see, it aligns today's date(Wednesday 03 March 2021) with Tuesday rather than Wednesday.

I haven't changed any code yet the CalendarView displays differently on Simulator and device. What could be causing this?

**Comment by Afterwalker99** [comment]
@yomagicdev I had the same problem too, seems like it's because of Locale for your phone. Some countries starts with Monday as the first day of the week while some country start with Sunday as the first day of the week. Make sure the dayOfWeekInitials takes in account the locale of the phone, hope this helps!

**Comment by francescodalsavio** [comment]
try to change the calendar configuration ->
Calendar.current -> Calendar.init (identifier: .gregorian),
This way it works for me correctly.

example:
let configuration = CalendarConfiguration (calendar: Calendar.init (identifier: .gregorian)...

I found that each location has a different (Calendar.current.firstWeekday), this is the cause of the error.

**Comment by ThasianX** [comment]
Great discussion here guys. Was in a rush when I initially created this library so wasn't able to fully test with calendars of different countries.
