### ISSUE TITLE
Resolving ElegantPages fails

### ISSUE THREAD

**Issue by Baldman68** [ThasianX/ElegantCalendar#33]
Hi, I'm trying to add ElegantCalendar as a Swift Package, but it keeps failing when it tries to resolve "Elegant Pages"

**Comment by ronin207** [comment]
I'm experiencing the same problem here. Would definitely like to implement it into my project!

**Comment by ThasianX** [comment]
Make sure that you are using Xcode 11 > and ensure that your project configuration supports this library
