### ISSUE TITLE
Error: `ElegantCalendar.xcassets` doesn't exist. Refer to the `README.md` installation on how to resolve this.

### ISSUE THREAD

**Issue by onlinedeveloper4u** [ThasianX/ElegantCalendar#35]
I run an example first time and this error produced. How to fix it ?

**Comment by samirsd** [comment]
same

**Comment by rbevans-ugh** [comment]
same

**Comment by ThasianX** [comment]
It means what it means. Go to the readme and follow the instructions

**Comment by samirsd** [comment]
this issue should probable be changed to an improvement then. ideally examples should just `run` out of the box with minimal work. the README is quite long, no one’s reading all that.

**Comment by ThasianX** [comment]
> this `issue` should probable be changed to an `enhancement` then. ideally examples should just `run` out of the box with minimal work. the README is quite long, no one’s reading all that.

Totally agree. However, this isn't always the case. I haven't worked on SwiftUI in a year and half now so things might've changed in regards to linking assets with a library. At the time when I made this though, there was no way around linking assets besides having library users manually do it.

In regards to your comment about the README being long, it's not. It's detailed. It addresses anything any user would want to know about how to use the library properly and is there to prevent self explanatory issues like these from popping up. I mean, the error you get from not linking the assets literally TELLS you exactly how to resolve it.
