### ISSUE TITLE
EventKit event and EKRecurrence rule

### ISSUE THREAD

**Issue by hungbv-0181** [ThasianX/ElegantCalendar#38]
Hi ThasianX, I want to display event of EventKit with recurrence in calendar, can ElegantCalendar display recurrence event? how to implement recurrence event?

**Comment by ThasianX** [comment]
yes it can. do your eventkit recurrence logic in `func calendar(viewForSelectedDate date: Date, dimensions size: CGSize) -> AnyView` and then display the same view for your recurrence event
