### ISSUE TITLE
Problem with Date 4th

### ISSUE THREAD

**Issue by wong-kene** [ThasianX/ElegantCalendar#40]
why is at every 4th of every month, there's always problems?

date cannot be clicked and color same with day of other month

Thanks..

**Comment by NandaRoma** [comment]
i can confirm because i am also experiencing this problem

**Comment by wang-jiaolong** [comment]
I also found this problem. Download the example and change the line 59 under the ExampleCalendarView.swift file, 'return day != 4' to 'return true' to solve the problem. I have not yet delved into the author's intention.

**Comment by ThasianX** [comment]
The example is just an example. It is meant to show the flexibility of the library, in this case allowing consumers to disable certain days from being clicked. You may want to do this if it is a holiday
