### ISSUE TITLE
iOS 15 Warnings in Xcode 13 when using ElegantCalendar

### ISSUE THREAD

**Issue by Danny-SS** [ThasianX/ElegantCalendar#43]
**Issue**
When running the Example project with Xcode 13, I am getting warnings in the console log:

`ForEach<Array<String>, String, ModifiedContent<ModifiedContent<Text, _FrameLayout>, _EnvironmentKeyWritingModifier<Optional<Color>>>>: the ID T occurs multiple times within the collection, this will give undefined results!` 

There are six of these in a series logged the calendar is displayed.

**iOS Version**
This only happens when running against iOS 15.  When I run against a simulator in iOS 14, it is quiet and I only get the expected messages from the Example project.

(This too is happening from my app that uses this package, but was easier and cleaner to verify this behavior in the include Example here).

I will try to hunt this down, but maybe someone else already has a solution.  The calendar does appear to be working iOS 15 despite these warnings, but worry something in SwitUI may break the cause of this in the future.

**Comment by ThasianX** [comment]
Expected as new iOS version = new stuff unaccounted for in the original code. If you can hunt the solution down and add the changes to this pull request, that would be great

**Comment by tompetit** [comment]
I was facing the same issue. Created a pull request, above

**Comment by ThasianX** [comment]
#48 fixes this
