### ISSUE TITLE
Segue from calendar date to another page

### ISSUE THREAD

**Issue by samuelbv9** [ThasianX/ElegantCalendar#44]
I can not figure out how to segue from the visit list cell to another view controller when I add a tap gesture recognizer to this part of the code. I would like to be able to go to another page on my app once the user selects a certain appointment on a date. Thank you

var visitsPreviewList: some View {
        
        VStack(spacing: 0) {
            ForEach(visits[range]) { visit in
                VisitCell(visit: visit)
                    .gesture(TapGesture().onEnded {
                        //Would like to segue to another ViewController here
                        print(visit.uid)
                    })
            }
        }
    }

**Comment by Kennpow** [comment]
Hey @samuelbv9, did you ever come up with anything for this scenario? I'm looking to do the same thing. For now I'm going to use sheets to get around, but I want to be able to wrap my calendar in a NavigationView and go to new pages when a date is clicked (or in the "list cell" is fine) as well.

**Comment by samuelbv9** [comment]
Yes I was able to wrap the calendar and another view into a larger mother view that changes from one screen to another based on a StateObject variable. 

`struct MotherView: View {
    
    @StateObject var viewRouter: ViewRouter
    
    var body: some View {
        switch viewRouter.currentPage {
            case .page1:
            return AnyView(CalendarView(viewRouter: viewRouter))
            case .page2:
                print("imageURL SELECTED: " + imageSelectedURL)
                return AnyView(PreviewPostView(viewRouter: viewRouter))
        }
    }
    
}`

then I just changed the var viewRouterVisits : ViewRouter I declared in VisitListView

`var visitsPreviewList: some View {
        
        VStack(spacing: 0) {
            ForEach(visits[range]) { visit in
                VisitCell(visit: visit)
                    .gesture(TapGesture().onEnded {
                        //segue to another ViewController
                        //set visit uid to be able to access image
                        print(visit.uid)
                        visitUID = visit.uid
                        getImageDetails()
                        viewRouterVisits.currentPage = .page2
                    })
            }
        }
    }`
