### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by metin-atalay** [ThasianX/ElegantCalendar#47]
Thank you for the beautiful library. When you open the library for navigation, it shows the month, and when you press back, it returns to the year display and then goes to the other screen.

**Comment by ThasianX** [comment]
I'm not sure what the issue is here? this functionality is correct

**Comment by metin-atalay** [comment]
We decided to use it in our project for its beautiful appearance. but it was a waste of our time. When you put it in a normal page, it works very well, but when you put it on the 2nd or 3rd page of the navigation view in a structure when you press the back button on the navigation bar, your library shows the yearly in the monthly display and then closes.

**Comment by yahyaizala** [comment]
i faced the same issue. I use  ElegantCalendarView(calendarManager: calendarManager).theme(CalendarTheme.yellowTheme).vertical()  like this. When clicking dismiss, it firstly shows previous month and then navigate to back.

**Comment by yahyaizala** [comment]
I realized the navigation issue occurs when initialMonth is setted.

**Comment by metin-atalay** [comment]
The owner closed the bug but it is a big bug @ThasianX @yahyaizala .

**Comment by yahyaizala** [comment]
Maybe it uses uikit I don't know why but somehow  in navigationview when we initialize in navigationlink class.  it insert itself to view. Maybe that is why it happens.

@metin-atalay i solved it when opening the calendar I show a progress and after initialization I fade calendar,
before page is dismissed I remove it with a state. That way its strange behavior not seen by user.

**Comment by yahyaizala** [comment]
Maybe it uses uikit I don't know why but somehow  in navigationview when we initialize in navigationlink class.  it insert itself to view. Maybe that is why it happens.

@metin-atalay i solved it when opening the calendar I show a progress and after initialization I fade calendar,
before page is dismissed I remove it with a state. That way its strange behavior not seen by user.

**Comment by metin-atalay** [comment]
@yahyaizala thanks for the info
