### ISSUE TITLE
startDate and endDate not recognized in example code.

### ISSUE THREAD

**Issue by aegladfelter** [ThasianX/ElegantCalendar#9]
I have installed the package according to the ReadMe instructions, but when I create a new swift file containing the sample code, the default values for startDate and endDate throw errors.
![Screen Shot 2020-08-06 at 6 54 37 AM](https://user-images.githubusercontent.com/23265287/89529100-bf7c5080-d7b1-11ea-8679-ad446579d751.png)

Am I missing something in the instructions? It seems like according to the docs that just executing this should default the start and end dates to todays value. Is there something that needs to be done here that isn't explicitly shown in ReadMe?

**Comment by sethi-ishmeet** [comment]
These are date objects and you can declare these variables in your view based your needs like:
```
private let startDate = Date().addingTimeInterval(TimeInterval(60 * 60 * 24 * (-30 * 36)))
private let endDate = Date().addingTimeInterval(TimeInterval(60 * 60 * 24 * (30 * 36)))
```
Adjust `TimeInterval` based on your specific needs. This should be fixed in documentation though. I will open a PR to do just that.

**Comment by ThasianX** [comment]
Thanks @sethi-ishmeet for helping out.
